### PR TITLE
packages upgrade

### PR DESCRIPTION
**Pull request by quantosapplications**

### CODE REVIEW

**Comment by MeAtPros** [comment]
when will it come to master?

**Comment by MeAtPros** [comment]
@quantosapplications Any update?

**Comment by MeAtPros** [comment]
@ahujaraghav Any update?

**Comment by quantosapplications** [comment]
We need to wait for @gauravguha

**Comment by geekruchika** [comment]
It's updated in version 0.2.0.
https://github.com/GeekyAnts/flick-video-player/tree/v0.2.0

And also, in this PR there were many native file changes. We missed .gitignore in commits, so it caused issues. 
Please feel free to open if there is an issue. Thank you.

**Pull request closed without merging**
