### PR TITLE
Update Flutter to 3.16.5 & Change to wakelock_plus...

### PR DESCRIPTION
**Pull request by h1amza**

### CODE REVIEW

**Comment by bladeofgod** [comment]
please merge this commit, tks. ;)

**Comment by h1amza** [comment]
@ahujaraghav @mrinaljain

**Comment by dxvid-pts** [comment]
+1

See this thread for more info: https://github.com/creativecreatorormaybenot/wakelock/issues/220

**Comment by soham-sharpsell** [comment]
+1
Please merge.

**Comment by rafampessoa** [comment]
+1

**Pull request merged**
