### PR TITLE
Cached video implementation

### PR DESCRIPTION
**Pull request by Bader-Al**
Just a cached video implementation for flick

### CODE REVIEW

**Comment by HugoHeneault** [comment]
Hey there! Is it normal that 1046 files are changed? 🤔 
You might ignore some of them

**Comment by geekruchika** [comment]
> Just a cached video implementation for flick



> Just a cached video implementation for flick

Hi @Bader-Al 

Can you please remove build folder, pubspec.lock, java build files, etc from the PR which are related to user's system. It will be easy for us to review the changes. Thanks in advance.

**Comment by Bader-Al** [comment]
I'm very sorry for this, as I'm new in contributing to open source. I will get those files removed ASAP.

**Comment by Bader-Al** [comment]
#44 

I re-pushed my changes to this PR. Sorry for the previous mistake.

**Comment by delfme** [comment]
Hi @Bader-Al this is great! 🚀👏
Would it be possible to also add pre-cache as in better_player. Indeed, feature should be even simpler. If precache option is enabled, Controller should start to cache the files for just X ms per file. X might be just 250ms, user can custom value as they need it. For us, that would bring flick player on par with better_player.

**Pull request closed without merging**
